### PR TITLE
Update npm test script

### PR DESCRIPTION
**Pull request by huei90**
Instead of searching the node_modules folder, you can use `mocha-phantomjs` to access the dependencies.

This looks better :smile:

### CODE REVIEW

**Comment by franciscop** [comment]
That looks much better, but then you need to manually install mocha-phantomjs first which should be documented in "Contributing.md". Could you add it, please?

**Comment by huei90** [comment]
@franciscop Usually we add a step `npm install` to download all the dependencies needed.

**Comment by franciscop** [comment]
@huei90 yes but if I'm not mistaken that doesn't install the global ones, only the local ones (the ones inside node_modules). For the global ones you need to manually add them, right?

**Comment by huei90** [comment]
For the global one we need `npm install -g mocha-phantomjs`
The test can run under `npm run`, it access the local one.

So yes, doesn't need to install the global one.

I will submit a new commit for the document later :smile:

**Comment by huei90** [comment]
DONE :beers:

**Comment by franciscop** [comment]
Thanks! :smile:

**Pull request merged**
