### PR TITLE
use push instead concat in unique

### PR DESCRIPTION
**Pull request by Xuefeng-Zhu**
concat will create an Array, which is not necessary

### CODE REVIEW

**Comment by franciscop** [comment]
But `push` retuns the [new length of the array](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/push) instead of the array itself. Do the tests pass in local? Something went wrong with CircleCI's PhantomJS, but I'm pretty sure some tests should be failing now (or they need to be extended).

**Comment by franciscop** [comment]
I would also say that this is mostly a micro optimization. I'll try running some tests*, but probably within the first few 1000s of elements there's no noticeable difference. If the code changed to the proposed one it'd be fine, but if it has to become more complex I am not sure if it's worth it. I'll post the tests when I get them.

*This is itself difficult because [different browsers are optimized differently](http://stackoverflow.com/a/13861357/938236) but I'll try anyway

**Comment by Xuefeng-Zhu** [comment]
Probably consider using Set
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

It is supported in IE11

**Comment by Xuefeng-Zhu** [comment]
`clean.indexOf(node) === -1 ` can be slow on large array. Set or object can solve the issue

**Comment by franciscop** [comment]
But unfortunately it is not well supported *in most mobile browsers*:

set element

Are you finding speed problems when using Umbrella? If so, what's the case/situation? While in general for arrays `indexOf()` might be slow, I think for the vast majority of the situations where Umbrella's unique() is used (small-ish arrays) it's totally acceptable.

**Comment by Xuefeng-Zhu** [comment]
OK. Thanks.

**Pull request closed without merging**
