### PR TITLE
FormData should not be paremeterized

### PR DESCRIPTION
**Pull request by triff**
When sending an ajax request we should avoid parameterizing `FormData` so that the proper Content-Type gets set by default.

I also took a stab at implementing some ajax tests using [sinon.js](http://sinonjs.org/)

### CODE REVIEW

**Comment by franciscop** [comment]
Awesome, also with the corresponding test. Thanks :+1:

**Comment by franciscop** [comment]
Do you think it's a good idea to migrate to pure json both on request and response as default?

**Comment by triff** [comment]
Do you mean instead of paramterizing the object?

It makes sense to allow json to be passed without being parameterized if the content-type is set. But the parameter string is easy to get working since backends handle it naturally. I wouldn't replace it completely

**Comment by franciscop** [comment]
I just mean the default, so this:

```js
ajax('/demo', { body: '{"a":"b"}' }, function(){});
```

Becomes the newdefault, while this:

```js
ajax('/demo', { body: 'a=b', headers: { 'Content-Type': 'application/x-www-form-urlencoded' } }, function(){});
```

Is the way to send it parameterized. About the back-ends:

- Node.js with [express can parse it and read it without any problem](http://stackoverflow.com/questions/10005939/how-to-consume-json-post-data-in-an-express-application):

    ```js
    app.use(express.bodyParser());
    ```

- [Ruby parses it automatically](http://stackoverflow.com/a/4360178/938236)

- With [PHP it's a bit more ugly](http://stackoverflow.com/questions/18866571/receive-json-post-with-php) but still easy:

    ```php
    $data = json_decode(file_get_contents('php://input'), true);
    ```

So yeah, major back-end technologies support it without much hassle, so I'll give it a go for 3.0

**Comment by triff** [comment]
It also might make sense to pass strings as `application/x-www-form-urlencoded` so that `.serialize()` can still be used. And send objects as `application/json`.

**Pull request merged**
