### PR TITLE
Trigger event when .on() selector contains the target element

### PR DESCRIPTION
**Pull request by triff**
Ensure that using `.on()` with a selector fires when children elements are targeted.

Simple example of the problem is when clicking on an element that has children. If the child is the target, the event won't fire.

### CODE REVIEW

**Comment by triff** [comment]
One issue with this is that the `event.target` will be the child element which was clicked. Which means it might be difficult to determine the desired element.

A solution could be to set something like `event.element` that always contains the element which matches the selector.

**Comment by franciscop** [comment]
So this would be for example for this:

```html
<ul>
  <li>
    <a>Hi</a>
  </li>
</ul>
```

```js
u('ul').on('click', 'li', function(e){
  e.target; // <a>
  e.currentTarget; // <ul>
  
  // proposed
  e.element; // <li>
});
```

Right? I think it still doesn't grant modifying the event prototype because there are many easy ways to retrieve it from inside the function.

With your bugfix, we should pass `e.target` to the callback instead of the current `target`. Now it's that way as `target` is the same as `e.target`, but with the new option we'd rather pass `e.target` so `this` is the clicked element in the context of the function.

**Comment by franciscop** [comment]
BTW, could you add a new test for your fix, please? You can just use the same code as I wrote above. So we can make sure that it isn't broken in the future.

**Comment by franciscop** [comment]
That looks awesome, thanks (:

**Comment by triff** [comment]
@franciscop I agree with not modifying the event. At the time (4am) I wasn't able to find a decent way to get the proper element when a few nested children. Now I realize that it's trivial with something like `.closest()`

**Comment by franciscop** [comment]
@triff that's exactly what I was thinking

**Pull request merged**
