### PR TITLE
Create wrap method

### PR DESCRIPTION
**Pull request by ianwhitedeveloper**
I'm still new to contributing to open source projects so I welcome feedback. Thank you for the opportunity to contribute!

### CODE REVIEW

**Comment by franciscop** [comment]
Hey awesome work, thanks. There are few things to note:

- I was wrong, it's better to just accept `'<div>'` as an argument and not `'div'`. This allows to change it in the future to standarize it with a selector. So the regex is not needed (and the documentation should be changed). If you cannot do this I'll do it no prpblem.
- It's a good idea to check how other methods work internally, since only the "external" ones are documented. For instance, `.join()` does a lot of the logic of the "newNodes" that you've setup so the code can be streamlined.
- Good reuse of the testing functions.
- What should happen if we do `wrap('<div><div></div></div>')`? Probably it should be stated that it is not supported *now* since it'd work in jquery (not closing future options and thus making it retrocompatible later on if we change it).

**Comment by Iawhite76** [comment]
Thanks for the feedback @franciscop ! I'll make the recommended updates as soon as I can.

**Comment by Iawhite76** [comment]
Hi @franciscop I tried my best to address your feedback. Please let me know if I'm on the right track. Also, if you don't mind, I'm going to look into the case of passing in a nested selector as an argument. Thanks!

**Comment by franciscop** [comment]
Awesome, I love it. It will be simplified even more when the `.replace()` method is working, since your

```js
node.
  parentNode.
  replaceChild(newNode, node);
```

Is basically the same as `.replace()`.

About the neested selector perfect, but there's a question to be answer that is which node to consider the "childmost". For instance, in this situation (jade for simplicity):

```jade
.a
  .b1
    .c1
  .b2
    .c2
      .d2
```

Should `c1` or `d2` considered for setting the content? `.c1` would be the one if we continue with the first child in the branch until we get to the last one, however `.d2` would be the chosen one if we continue executing `.children()` until we get the last one. How should we decide? Is any method better than the other? It seems like a totally arbitrary decision now (without using `.wrap()` in depth yet). How does jQuery do it? Is it the best way?

**Comment by Iawhite76** [comment]
Good question, @franciscop.  I tried a crude little experiment with jQuery wrap and it looks like it wraps the target node in the "first last child" it finds, or in ```c.1``` from your example above. 


jquery-wrap-test

**Comment by franciscop** [comment]
Awesome, so with a combination of `.children()` and `.first()` you might be able to do it :thumbs-up:

**Comment by ianwhitedeveloper** [comment]
@franciscop I added support for nested selector args. Still have some cleanup to do but let me know how to improve when you have the time. Thanks!

**Comment by franciscop** [comment]
Awesome, a couple of details:

- console.warn is not standard
- why do you need the try{}catch in this situation?
- can `.firstElementChild()` be replaced for `.children().first()`? (probably it has a couple of advantages and it's only slightly slower).
- don't define new global functions, and much less inside the same file. Each file in `/plugins` only exports one function (with the name of it). The exceptions are fn.parseJson and fn.ajax. So either define the function inside the method itself (recommended) or do it as a new plugin.

**Comment by ianwhitedeveloper** [comment]
Thanks again for the feedback @franciscop. I completely agree with your comment about not creating new global functions and I'm glad I now know you recommend defining the function within the method as I was going down the path of adding it as a library method so I'll rethink that approach. This branch is still a work in progress and I will try to get this code cleaned up this week.

**Comment by franciscop** [comment]
Perfect, thanks. Normally a rule of thumb is setting up a library method if it's going to be widely reused (privately or publicly) and internal function (private) if it's going to be used only by that method. In this situation I think it will only be used once, so private would be preferred.

**Comment by ianwhitedeveloper** [comment]
@franciscop At the moment I can't think of a way to incorporate `.children().first()` into the helper function `findDeepestNode`. I can't use those methods in the helper function since it's working on DOM nodes and not umbrella js. instances, and if I do `u(selector).children().first()` it returns the first child, but there is still a nested element within.

I feel like I'm missing something -  could you please point me in the right direction? Thanks!

**Comment by franciscop** [comment]
I meant using it instead of `firstElementChild`, however the way you use it is better so now it's perfect. I'll check the code locally and accept it, thanks!

**Pull request merged**
