### PR TITLE
Implemented .last()

### LINKED ISSUE #1: Create .last()
> This is an issue ready for newcomers and people who want to learn how to contribute to an open source project. Read more about this type of issues in [Up For Grabs](http://up-for-grabs.net)

Create a function that returns the last of the matched nodes or false if there's no one. To start contributing:

- Clone the repository
- Create the corresponding folder in `src/plugins`
- Execute `grunt watch` in the terminal. Make sure you have [phantomjs](http://phantomjs.org/) installed first.
- Create the three files, `last.js`, `documentation.md` and `test.js`
- In `last.js` add the code needed to execute it
- Then (or before if you are into TDD) add the needed tests in `test.js`. After adding them all, open tests.html in your browser, which should show a passing/failing for your tests. Or check the terminal, since grunt should run tests now too.
- Add the `documentation.md` needed to use it
- Send a Pull Request and I'll provide feedback on the code

Note: Check out `.first()` code to create `.last()`

### PR DESCRIPTION
**Pull request by nileshr**
Implemented .last() method to fix #1 
P.S - This is my first time working with git and also contributing to open source so correct me if I've done anything incorrectly.

### CODE REVIEW

**Comment by franciscop** [comment]
Yeah, this is awesome, thank you so much for doing the pull request! It looks great, a couple of improvements:

-  in `src/plugins/last/documentation.md`, you forgot to change the description, it reads "*Add html class(es) to all of the matched elements.*" but this is not the real description for this function
- in the same file, I would say that `### Related` isn't `removeClass` and `hasClass`, but it's instead `first()`
- I'm not sure about the external pull requests, but if you add `fixes #3` to the commit message, then when I accept it this issue will be closed automatically. This is not needed at all, just a tip (:

A couple of questions, how did you find about Umbrella JS? Did you have any problem doing this?

**Comment by nileshr** [comment]
I seemed to have overlooked the documentation.md file. Anyways I'll make the changes and commit it. Should I put fixes #1 for this commit message? 
I found Umbrella JS through up-for-grabs.net and it seemed very interesting so I decided to start contributing here :)

**Comment by franciscop** [comment]
Sure thing, add it so it gets closed automatically (:

Thanks

**Comment by franciscop** [comment]
Also, to be fair `.first()` tests are quite small, if you could add a couple of relevant tests to `.last()` it'd also be great such as:

- Test that `u('.non-existing').last()` returns false
- Test that `u('li').last()` really returns the last of the matched nodes (not just a LI node).

**Comment by nileshr** [comment]
I've fixed the documentation.md with the suggested changes.
I'll add more tests when I get free time later.

**Comment by franciscop** [comment]
This looks great, thank you! I'll merge it ASAP

**Pull request closed without merging**
