### PR TITLE
Adding a .toggleClass() method

### LINKED ISSUE #7: add .toggleClass()
Please consider adding the jquery method .toggleClass. It is one of the most used jquery methods in many code bases I've worked on for its simple ability to use a boolean to set whether or not an element has a class.

Otherwise, everyone using your library will likely have to continually write code like:

```javascript
let toggle = true;

if (toggle && !u("div").hasClass("super-awesome-class")) {
  u("div").addClass("super-awesome-class");
} else if (!toggle && u("div").hasClass("super-awesome-class")) {
  u("div").removeClass("super-awesome-class");
}
```

When you could just have:

```javascript
let toggle = true;
u("div").toggleClass("super-awesome-class", toggle);
```

Would you accept a PR with this feature?

### PR DESCRIPTION
**Pull request by blaketarter**
This fixes #7

### CODE REVIEW

**Comment by blaketarter** [comment]
I will say that I want to implement the optional parameter that toggles the class depending on a provided conditional, I figured I might get this up there for now and augment the method when I have more time. If need be we can leave this un merged until I get to that part of it.

**Comment by franciscop** [comment]
Hey, thank you so much for the pull request. Unfortunately [no IE supports the second parameter for toggle()](http://caniuse.com/#search=classList), which I think it's one of the main advantages for this method. However, jquery's `toggleClass()` gives a great clue about how it could be implemented:

```js
$( "#foo" ).toggleClass( className, addOrRemove );
```

is equivalent to:

```js
if ( addOrRemove ) {
  $( "#foo" ).addClass( className );
} else {
  $( "#foo" ).removeClass( className );
}
```

What do you think about my last comment in [add .toggleClass()](https://github.com/umbrellajs/umbrella/issues/7) issue? We could depart from the standard *Class functions for simplicity (which I favor) or make it more flexible, but also complex and potentially confusing and error-prone.

**Comment by blaketarter** [comment]
I think making it match `classList.toggle()` would make the most sense, where it accepts 2 parameters with the first being a single class, separated by commas, or separated by a space. That would allow us to have  our `.toggleClass()` use `classList.toggle()` internally if it's available and then fallback to just `.addClass()` or `.removeClass()`.

**Comment by franciscop** [comment]
I agree except with

> That would allow us to have our .toggleClass() use classList.toggle() internally if it's available and then fallback to just .addClass() or .removeClass().

One of the reasons for making Umbrella so small is the lack of pollyfills/polymorphism where we check if it works for the specific browser and just use the version that works best for all. However, since there are two footprints, something like this should be needed:

```js
toggleClass = function(classes, force) {

  // The code you already made
  if (force === undefined) {
    return this.each(function(node){
      // use the classList.toggle()
    }
  }
  return this.[force ? 'addClass' : 'removeClass'](classes);
}
```

**Comment by franciscop** [comment]
BTW I just added a convenient method for addClass and removeClass that is also useful here, `eacharg`. You could implement it in your current code like this:

```js
u.prototype.toggleClass = function(classes){
  
  return this.eacharg(classes, function(el, name){
    el.classList.toggle(name);
  });
};
```

**Comment by blaketarter** [comment]
That makes sense, alright this is what I had when I just noticed you responded with a code example and a new method which I will work in there. 

```js
u.prototype.toggleClass = function(classes, addOrRemove){
  
  // Normalize the classes to a simple array
  classes = this.args(classes);

  //check if addOrRemove was passed
  if (typeof addOrRemove === 'boolean') {

    // return the corresponding Umbrella method
    return (addOrRemove) ? this.addClass(classes) : this.removeClass(classes);
  }
  
  // ...the regular toggleClass code
});
```

**Comment by franciscop** [comment]
:+1: perfect

**Comment by blaketarter** [comment]
@franciscop do you think it needs more work? I feel like its solid.

**Comment by franciscop** [comment]
It looks great, I'll merge it ASAP, thank you!

**Comment by franciscop** [comment]
Merged. I will bump the minor version. I optimized a couple of things:

```js
// Original
if (typeof addOrRemove === 'boolean')

// New
if (!!addOrRemove === addOrRemove)
```

While it might seem the same, when minimized they become:

```js
// Original
"boolean"==typeof b

// New
!!b===b
```

And they behave in the same way (tests added for that). Also:

```js
// Original
a=this.args(a),b?this.addClass(a):this.removeClass(a)

// New (also no need for this.args)
this[b?"addClass":"removeClass"](a)
```

That one was not really necessary now that I see the bytes saved, however now that I did it there's no need to revert (since it's slightly smaller and still legible).

**Comment by blaketarter** [comment]
Looks good to me :thumbsup:

**Pull request merged**
