### PR TITLE
adds replace function to the library: fixes issue #56

### PR DESCRIPTION
**Pull request by paxmugisha**

### CODE REVIEW

**Comment by paxmugisha** [comment]
Hi @franciscop  here is the pull request. Any feedback is weclome :) I am not sure the way I created new node is the most appropriated. 
``` js
newNode = u(html).first();
```
I had to call the first method as the u() constructor is generating an extra empty node

**Comment by franciscop** [comment]
Hi @paxmugisha , sorry for answering so late.

What do you mean by *the u() constructor is generating an extra empty node*? Can you provide a test case, please? If it's a bug it should be fixed for sure. Also I [cannot reproduce what you say](https://jsfiddle.net/franciscop/a0ptoboh/). The constructor doesn't generate the node(s) itself, it generates an object which contains the nodes in the variable `.nodes` and the first one can be accessed with `.first()` or just `.nodes[0]`.

About the code, the main issue I see is code duplication. For instance, this is repeated almost identically:

```js
return this.join(function(node){
  newNode = u(newValue).first();
  node.parentNode.replaceChild(newNode, node);
  return newNode;
});
```

While your way is probably better for performance, we are taking a *size first* approach so code size is more important than speed unless there's a sizeable difference. Similar with errors, you should be checking for expected (as in documented) situations and just let it fail otherwise so the developer can handle it (one of the most frustrating things from jQuery is that it just swallows the errors, like in the situation `return this;`, so it becomes more difficult to debug). So you could instead do something like this:

```js
return this.join(function(node){
  if (typeof newValue === 'function') {
    newNode = newNode(node);
  }
  newNode = u(value).first();
  // ...
});
```

A single `typeof` conditional is probably irrelevant (in the μs) speed-wise as we are manipulating the DOM (in the ms). However feel free to prove me wrong with some test in Umbrella or in http://jsperf.com/ :smile:

**Comment by paxmugisha** [comment]
Hi @franciscop no worries :) I don't know how I missed that duplicated block. I totally agree on the size first approach and on the fact that the code should simply break if the argument is invalid to avoid silent errors. What I mean by the extra node is illustrated by the code below 
``` js
var newButton = u('<button class="update">Update<button>');
```
In this case I would expect newButton.nodes to be valued to 
``` js 
 [<button class=​"update">​Update​</button>​​]
```
But it is actually valued to 
``` js 
 [<button class=​"update">​Update​</button>​, <button>​</button>​]
```
An extra empty button (``` js  <button>​</button> ```) is added. 
I couldn't figure out under which conditions it is occurring. I can investigate on it if you confirm it is an issue :) let me know

**Comment by paxmugisha** [comment]
Pull request updated

**Comment by franciscop** [comment]
Oh I thought so, you are not closing the button, you have two opening tags `<button>` in your code. If you write `u('<button class="update">Update</button')` (notice extra `/`) it should be fine

**Pull request merged**
