### PR TITLE
Add .scroll(): go to the first matched element- issue #30

### PR DESCRIPTION
**Pull request by CraigDMcKenna**
How is this?  Let me know if I need to make any changes.  Thanks.

### CODE REVIEW

**Comment by franciscop** [comment]
It looks great, a couple of notes though:

1. Returning `this.first()` is not consistent with any other method. We could just return `this` (recommended) so the user can keep chaining, or otherwise not return anything (not recommended).

2. If it doesn't scroll at all, then the test passes since `.top` is 0. This is not desirable, you could force it:

```js
function didScroll(el) {
  return window.innerHeight + window.scrollY >= document.body.offsetHeight;
}
```

If the content is too short you could add elements to make the height larger than the window height. There's [a grunt option to set the viewport size](https://github.com/jdcataldo/grunt-mocha-phantomjs#passing-options-to-mocha-phantomjs) which might also help.

3. `didScroll()` seems to check if the window scrolled (from the name), but it also attempts to do `scroll()`. The name is confusing and it could be separated in two pieces like this:

```js
it('can scroll to the element', function() {
  expect(didScroll()).to.equal(false);
  u('li').scroll();
  expect(didScroll()).to.equal(true);
});
```

4. There's no testing of the return value

**Comment by CraigDMcKenna** [comment]
All great points.  Thank you.

**Comment by CraigDMcKenna** [comment]
What do you think of this?

```js
it('should return this Umbrella Object', function() {
    expect(u('li').scroll().prototype).to.equal(u('li').prototype);
});
```

**Comment by CraigDMcKenna** [comment]
Not exactly as you suggested but I think it works. I'm mostly ignorant of grunt.

Were you suggesting that I set the viewport size directly in the Gruntfile?  Because it seems that this would set the viewport for all tests, no?

**Pull request merged**
